inject request stack for symfony 6
jorisdugue/h5p-bundle pull request #44
Opened 2023-08-21 15:28 UTC by tuxes3

To support symfony 6

2023-08-22 14:28 UTC, jorisdugue requested changes
Thanks for making these changes but there are a few changes to make to improve code quality and readability

2023-08-22 14:28 UTC, jorisdugue commented on Core/H5PSymfony.php
> +        if ($this->session === null || !$this->session->getFlashBag()->has($type)) {
replace this row is better 😄 

```suggestion
        if (!$this->session || !$this->session->getFlashBag()->has($type)) {
```

2023-08-22 14:46 UTC, tuxes3 commented on Core/H5PSymfony.php
> +            $this->session = $requestStack === null ? null : $requestStack->getSession();
Hey. I had a case where `$requestStack->getSession();` did throw the `SessionNotFoundException`. Also there is no method to check if the session is present or not. Furthermore we did change the code to support no session, which would be the case here if no session was found!

For these reasons i did not remove the `try ... catch`.

2023-08-23 06:56 UTC, jorisdugue commented on Core/H5PSymfony.php
> +            $this->session = $requestStack === null ? null : $requestStack->getSession();
Hey @tuxes3 ,
I kinda suspected that, we have no choice but to silence the exception for once otherwise it won't work

2023-08-23 06:58 UTC, jorisdugue approved these changes
Thanks for the edits, looks good to me :)

2023-08-23 06:58 UTC, merged